schema_version: 1

context:
  name: PyGT
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/PyGT-${{ version }}.tar.gz
  sha256: 6bb3219af8d59ffc3f8a61988165f8b93c5ec88caaef5c6d0f6dcf067d0cde80

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - scipy >=1.5
    - numpy >=1.17
    - matplotlib-base >=3
    - tqdm >=4.47
    - pathos >=0.2

tests:
  - python:
      imports:
        - PyGT
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Graph transformation and reduction in Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tomswinburne/PyGT

extra:
  recipe-maintainers:
    - tomswinburne
    - jan-janssen
